name: Deployment - Reusable workflow
on:
  workflow_call:
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true
    inputs:
      mongodb-url:
        required: true
        description: 'MongoDB connection string'
        type: string
      kubectl-version:
        description: Provide the required kubectl version
        required: false
        type: string
        default: v1.26.0
      k8s-manifest-dir:
        description: Directory containing the kubernetes manifests files
        default: kubernetes/
        required: true
        type: string
      environment:
        description: Environment to deploy the application
        required: true
        type: string
        default: Development

jobs:
  reuse-deploy:
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.set_ingress_url.outputs.URL }}
    runs-on: ubuntu-latest
    outputs:
      URL: ${{ steps.set_ingress_url.outputs.URL }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: '${{ inputs.kubectl-version }}'
      - name: Set Kube config
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s-kubeconfig }}
      - name: Fetch kubernetes Cluster details
        run: |
          kubectl version
          echo -------------------
          kubectl get nodes
      - name: Save Nginx ingress controller IP as a GITHUB Environment variable
        run: |
            echo "INGRESS_IP=$(kubectl -n ingress-nginx get services nginx-ingress-ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
      - name: Replace tokens in Manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}
      - name: Check files
        run: |
          cat ${{ inputs.k8s-manifest-dir }}*.yaml
      - name: Create mongoDB secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ inputs.mongodb-url }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
      - name: Deploy to Development Environment
        run: |
          kubectl apply -f ${{ inputs.k8s-manifest-dir }}
      - name: Set App Ingress Host URL
        id: set_ingress_url
        run: |
          echo "URL=$(kubectl -n ${{ vars.NAMESPACE }} get ingress solar-system -o jsonpath='{.spec.rules[0].host}')" >> $GITHUB_OUTPUT