name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
      name: Unit Testing
      strategy:
        matrix:
          nodejs_version: [18, 20]
          operating_system: [ubuntu-latest, windows-latest]
          exclude:
            - nodejs_version: 18
              operating_system: windows-latest
      runs-on: ${{ matrix.operating_system }}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}
        - name: Cache NPM dependencies
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install Dependencies
          run: npm install
        - name: Unit Testing
          id: node_js_unit_test
          run: npm test   
        - name: Archive Test Result
          if: failure() && (steps.node_js_unit_test.outcome == 'failure' || steps.node_js_unit_test.conclusion == 'success')
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Setup NodeJS Version - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Cache NPM dependencies
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install Dependencies
          run: npm install

        - name: Check code coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive Code Coverage
          uses: actions/upload-artifact@v3
          with:
            name: Code-Coverage-Report
            path: coverage
            retention-days: 5
